// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EFCoreApplication.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class DeviceEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "EFCoreApplication.Device",
                typeof(Device),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var deviceId = runtimeEntityType.AddProperty(
                "DeviceId",
                typeof(Guid),
                propertyInfo: typeof(Device).GetProperty("DeviceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Device).GetField("<DeviceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var deviceName = runtimeEntityType.AddProperty(
                "DeviceName",
                typeof(string),
                propertyInfo: typeof(Device).GetProperty("DeviceName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Device).GetField("<DeviceName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var latestLogTime = runtimeEntityType.AddProperty(
                "LatestLogTime",
                typeof(DateTime),
                propertyInfo: typeof(Device).GetProperty("LatestLogTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Device).GetField("<LatestLogTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var latestReportedAddresses = runtimeEntityType.AddProperty(
                "LatestReportedAddresses",
                typeof(List<IPAddress>),
                propertyInfo: typeof(Device).GetProperty("LatestReportedAddresses", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Device).GetField("<LatestReportedAddresses>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            var latestReportedAddressesElementType = latestReportedAddresses.SetElementType(typeof(IPAddress));

            var key = runtimeEntityType.AddKey(
                new[] { deviceId });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { deviceName },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Devices");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
