// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace EFCoreApplication.CompiledModels
{
    public partial class DeviceOnlineLoggingContextModel
    {
        private DeviceOnlineLoggingContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("dbcbe7ff-c9ff-496e-a7f6-458bd7fb753a"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var device = DeviceEntityType.Create(this);
            var onlineLog = OnlineLogEntityType.Create(this);

            OnlineLogEntityType.CreateForeignKey1(onlineLog, device);

            DeviceEntityType.CreateAnnotations(device);
            OnlineLogEntityType.CreateAnnotations(onlineLog);

            AddAnnotation("ProductVersion", "10.0.2");
        }
    }
}
