// <auto-generated />
using EFCoreApplication;
using EFCoreApplication.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DeviceOnlineLoggingContext), typeof(DeviceOnlineLoggingContextModel))]
