// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreApplication.Migrations
{
    [DbContext(typeof(DeviceOnlineLoggingContext))]
    [Migration("20260121150659_RemoveUnnecessaryDeviceNameInOnlineLogs")]
    partial class RemoveUnnecessaryDeviceNameInOnlineLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestLANIPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LatestLogTime")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceName")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("OnlineLog", b =>
                {
                    b.Property<int>("OnlineLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LANIPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("OnlineLogId");

                    b.HasIndex("DeviceId");

                    b.ToTable("OnlineLogs");
                });

            modelBuilder.Entity("OnlineLog", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany("OnlineLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Navigation("OnlineLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
